### ISSUE TITLE
Explain middleware filters in Guide

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#11]
Currently middleware filters are only introduced in blog:

http://starcounter.io/nightly-changes/introducing-middleware-filters-starting-with-build-2-0-3100-3/
http://starcounter.io/nightly-changes/addingskipping-middleware-filters/

They should be also explained in Guide: http://starcounter.io/guides/network/

**Comment by alemoi** [comment]
Will do that! Thank you for creating the issue!

**Comment by alemoi** [comment]
Fixed! Thanks for reporting!
