### ISSUE TITLE
Improve an explanation for TCP socket

### ISSUE THREAD

**Issue by dan31** [Starcounter/starcounter.io#111]
In here: http://starcounter.io/guides/network/tcp-sockets/, for the customer it wasn't obvious what exactly to do when received a call in a handler. Is it just a typical scenario is to maintain some dictionary of ```tcpSocket```s inside a handler (either a DB-class based, or ```ConcurrentDictionary``` of a kind) and use it to retrieve the corresponding job state. The question comes with an idea to stream files over TCP. Some short elaborative example in the same article looks to be desired. @alemoi, WDYT?

**Comment by alemoi** [comment]
I will add some more examples. Thank you.

**Comment by alemoi** [comment]
Added a small example for both UDP and TCP sockets.
