### ISSUE TITLE
Documentations says Person but example says App1Class. App2Class

### ISSUE THREAD

**Issue by pluppplupp** [Starcounter/starcounter.io#116]
http://starcounter.io/guides/sql/sql-isolation/

![2015-12-17_15-39-20](https://cloud.githubusercontent.com/assets/1765023/11872230/8810f908-a4d4-11e5-94b3-2a6d58ccc296.png)

**Comment by warpech** [comment]
@alemoi, since this is your page, can you update it? We should always illustrate using real-life names, such as `Person` over artificial, such as `App1Class`.

**Comment by alemoi** [comment]
Ohh yes. Thank you for finding this.
