### ISSUE TITLE
Compatibility with IE11

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/starcounter.io#12]
Many Windows servers today run IE11 as their default browser. However, the Starcounter.io "other versions" downloads page appears to be using Polymer. This is unfortunate because IE11 seems to have no understanding of Polymer templates, so the site is unusable.

**Comment by miyconst** [comment]
Thank you for reporting this, I will try to fix it.

**Comment by miyconst** [comment]
@mtornwall could you please provide some more info? Screenshot, full browser version?

The page works fine for me under Win8.1 IE11 & Win Server 2012 IE10, unfortunately I don't have  Win Server 2012 R2 which has IE11 by default.

**Comment by mtornwall** [comment]
Silly me. The problem is not with IE itself but with the default security configuration on Windows Server 2012 R2, which blocks JavaScript so that the polyfills cannot run. Not much to do about that I guess?

**Comment by miyconst** [comment]
Yes, there is no way to change browser settings from a webpage.

The most I can do is to add a message:

```
Starcounter.io website requires JavaScript to work properly.
```

**Comment by mtornwall** [comment]
That's good enough, I think.

**Comment by miyconst** [comment]
Done.
