### ISSUE TITLE
Left menu pushed below the content.

### ISSUE THREAD

**Issue by MLidstrom** [Starcounter/starcounter.io#121]
When making the web page narrower the left most menu is pushed below the content. Maybe fixed with min-width in the fusion-row css class.

**Comment by miyconst** [comment]
Could you provide a screenshot?

**Comment by MLidstrom** [comment]
This is after making the page narrower.

![4](https://cloud.githubusercontent.com/assets/538395/12484475/c466c292-c05a-11e5-93e0-7e3cdfb37e59.png)

**Comment by warpech** [comment]
Fixed. There is a similar problem with the top menu, but that one requires updating the theme: https://github.com/Starcounter/starcounter.io/issues/128
