### ISSUE TITLE
Problem when renaming *.json.cs

### ISSUE THREAD

**Issue by jakubklekota** [Starcounter/starcounter.io#131]
Hello,
It's problem when renaming file in VS2013 - *.json.cs in app.

When rename from ex. ```settings.json.cs``` to ```newSettings.json.cs``` in code behind stay old name.

It's very misleading

**Comment by miyconst** [comment]
cc @per-samuelsson

**Comment by per-samuelsson** [comment]
@jakubklekota 

Have you tried renaming the `json`, instead of the `json.cs`? I think that is the support we have.

**Comment by jakubklekota** [comment]
@per-samuelsson 

Please create new starcounter application project. Add new item in solution - Starcounter -> Starcounter Typed JSON with Code-behind. Change ```json``` name. Next ```json``` and ```json.cs``` files has been changed, but when open ```json.cs``` file partial class have old name

**Comment by chrhol** [comment]
@jakubklekota,  @per-samuelsson: The problem I think is that there is no refactoring triggered when renaming the file so the actual name of the class is not changed, which differs from how renaming standard files work where you get a question if you want to change the name of the class as well.

I thought there was an (old) issue about this on the starcounter issuetracker, but I cannot find it. I will add a new one so we keep track of it, and see what can be done.

**Comment by warpech** [comment]
Thanks for reporting. 

@chrhol can you cross-link to that issue or create a new one? 

Afterwards think this one can be closed, because this issue tracker is for website problems.

**Comment by chrhol** [comment]
Added issue https://github.com/Starcounter/Starcounter/issues/3319. Will close this one then.
