### ISSUE TITLE
Tutorial screenshots needs updating

### ISSUE THREAD

**Issue by MLidstrom** [Starcounter/starcounter.io#133]
The screenshots of the launcher shows the dashboard menu item. In recent versions of the launcher the dashboard isn't visible until you add a menu item. An example on the bottom of this page:
http://starcounter.io/tutorials/invoicedemo-part-3/3-2-run-invoicedemo-inside-launcher/

**Comment by warpech** [comment]
This is almost correct - actually currently in Launcher there is no such thing as "dashboard". The screenshots should be updated to only show "menu" and "launchpad".

**Comment by warpech** [comment]
Updated all of the screenshots in InvoiceDemo Tutorial Part 3 that were outdated. Thanks for reporting!
