### ISSUE TITLE
Update the InvoiceDemo tutorial

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#2]
Some images and code snippets in the [InvoiceDemo tutorial](http://starcounter.io/tutorials/1-introduction-to-part-1/) (part 1 and 2) are not up-to-date with the current [code](https://github.com/Starcounter/InvoiceDemo). Please update. Make changes to the text as well if you feel like.

**Comment by miyconst** [comment]
I went through the tutorials and fixed images/code snippets. Also fixed some links and spelling errors.

**Comment by miyconst** [comment]
Added Prev/Next buttons to the bottom of each page.

**Comment by warpech** [comment]
Thanks, closing!
