### ISSUE TITLE
Duplicate content on JSON pages

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#24]
These two JSON pages contain some duplicate content about custom property binding:

http://starcounter.io/guides/json/populate-json-with-database-data/
http://starcounter.io/guides/json/json-data-binding/

I think that the custom binding part can be removed completely from http://starcounter.io/guides/json/populate-json-with-database-data/

**Comment by chrhol** [comment]
I did as you suggested, I removed the sections from the first document explaining custom bindings. It could probably be reworked to get a better flow between the documents but at least we don't explain the same thing in different places for this.

**Comment by warpech** [comment]
Thanks!
