### ISSUE TITLE
Use the phrase "Starcounter apps" consistently

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#25]
Currently in few places, the term "Polyjuice apps" is used sometimes. The technology behind the apps is called Starcounter and the term "Starcounter apps" should be used in such places.

This issue applies to starcounter.io as well as all our wikis and READMEs.

**Comment by miyconst** [comment]
@warpech can this one be also closed?

**Comment by warpech** [comment]
I created a page http://starcounter.io/guides/web/what-is-an-app/ . I think it can be closed now
