### ISSUE TITLE
Add search to the Docs section

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter.io#26]
The Blog section has search field, which is very useful. It would also be very helpful on the Docs section, especially now, when we migrate content from WiKi and change terminology from `Polyjuice` to `Starcounter`.

cc @warpech

**Comment by warpech** [comment]
Currently search functionally actually searches all .io content (Blog and Docs included), but the search result page looks very poor.

I will try to improve that by using some plugin.

**Comment by warpech** [comment]
I have installed Revelanssi plugin, and it is improved, but the problem with it that it highlights search results only in blog posts, not in pages.

I will try my luck tomorrow with the following apps:
https://wordpress.org/plugins/better-search/
https://wordpress.org/plugins/search-everything/
https://wordpress.org/plugins/wp-ultimate-search/

**Comment by warpech** [comment]
I installed Better Search plugin. It has highlighting, but now I am worried about search relevancy. I will live it for now.

**Comment by warpech** [comment]
I guess it is as good as it gets with WordPress. Please reopen if you have more ideas for improvements
