### ISSUE TITLE
Change polyjuice-include to starcounter-include

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#27]
On starcounter.io there are 3 articles that need change from polyjuice-include to starcounter-include:

http://starcounter.io/nightly-changes/unified-convention-for-partials-in-starcounter-2-0-3193-3/
http://starcounter.io/guides/web/partials/
http://starcounter.io/guides/web/more-on-partials/

Can you do that @miyconst?

**Comment by miyconst** [comment]
I have replaced all of the `polyjuice-include` with `starcounter-include` and some *Polyjuice* with *Starcounter*.

But the pages still should be cleaned up from Polyjuice terminology.

**Comment by warpech** [comment]
That's an ongoing effort :) Closing this one, thanks!
