### ISSUE TITLE
Make use of deployment/HA answer provided by Dan

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#36]
In answer about HA topology by email, Dan responded:

Okay, I see :) Some answer is this:

* Most of customers today use either in-house installations or in-cloud in Amazon, Azure or dedicated servers at providers like GleSYS. We will use an example of Amazon.

* Windows VM with at least 2 cores is required to run Starcounter, and RAM enough to store your data (current largest customers don't exceed 50 Gb in runtime) + double-size of the maximum in-memory data size to store the snapshots and log entries on disk.

* Starcounter is not enabled to run on 1-core machines, because of communication overhead introduced when running Starcounter processes on one physical core. Starcounter is optimised to scale on multi-cores. 

* No other special hardware requirements, all modern cloud hardware is capable of running Starcounter. Starcounter doesn't operate on a raw-physical level of storage devices, no special hardware appliance is needed.

* Failover machine for HA in case of one machine failure: install a 2-machine cluster with 10 Gb ethernet connection between machines, make one of these:

a) Windows 2016 Storage Replica (sync and async replication of storage devices between two Windows machines over network on disk block-level)

b) Starcounter replicator (enterprise feature, deployed by Starcounter on per-customer basis)

* Provide HA on a single machine for persistent storage failures: use simple RAID-1 over HDDs for high availability. Starcounter is providing ACID by streaming log of changes to disk (as all modern in-memory technologies do). Modern HDDs enable for writing terrabytes of data to disk in seconds in sequential mode. You don't need to do SSDs for performance.

* Do regular backup on your local machine or SAN network. Remember that backing up and hot failover are not equal things: in general, you might end up with hot failover of a corrupted database if you corrupt your data by a human factor (uploading of wrong application to production and alike). Backups save you from human factor failure, failover is used for hardware factor failure.

* Use Windows Shadow Copy to backup Starcounter images in a scope of the same machine.

* You don't need to do round-robin and load-balancing for HA to prevent denial of service at high loads, since Starcounter is capable of millions of TPS out of the box on a single server (http://www.starcounter.com/in-memory-application-platform/starcounter-performance/).

Let's repurpose that on the website

**Comment by dan31** [comment]
I'm writing a better version that addresses backup scheme through Shadow Copy.

**Comment by dan31** [comment]
Wrote an article: http://starcounter.io/guides/tools/run-starcounter-in-production/ .

**Comment by warpech** [comment]
Great! I have added a blog post about it: http://starcounter.io/website-news/running-starcounter-in-production/
