### ISSUE TITLE
Fix page editor to don't remove white space from code snippets

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter.io#4]
Currently the MD code snippets are supported, but visual editor cuts all of the white spaces, which makes code unreadable.

**Comment by warpech** [comment]
The fix that I use is not to use the visual editor. Any better ideas?

**Comment by miyconst** [comment]
I also did like this, but if you switch tab by accident, then all white spaces will be removed.

**Comment by miyconst** [comment]
There should be an option for the html editor to don't remove white spaces. The WordPress developer should be asked for this.

**Comment by warpech** [comment]
By WordPress developer do you mean http://automattic.com/? I am sure they heard about this issue, which is quite an old problem: http://wordpress.stackexchange.com/questions/90065/preserve-white-space-in-page

Solution is not to use visual editor or replace it using some plugin. Besides that, I think that visual editor is not compatible with Markdown plugin anyway.

Radical solution: Go to Admin->Users->Your Profile and check the box for 'Disable visual editor...'. Sadly, this breaks Fusion Composer, which is used by some pages.

**Comment by miyconst** [comment]
By developer, I meant the person who set up the website. Anyway, that is not a big deal, I will just use the text editor instead of visual.
