### ISSUE TITLE
Improve syntax highlighting

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#5]
I think that plugin that we currently use (Crayon) does not give optimal results with C# and HTML.

Let's consider using some other, e.g. https://wordpress.org/plugins/wp-code-highlightjs/ . First, we need to check if it colors HTML Custom Elements better than Crayon

Also, the colors could be improved. These guys have it nicely aligned with their theme: https://parse.com/docs/ios/guide

**Comment by warpech** [comment]
Done. Replaced Crayon with WP Code Highlight.js, which has nicer themes. Used dark color theme that has more character.

**Comment by dan31** [comment]
Looks good!
