### ISSUE TITLE
Update pages to reflect changes in SQL apps isolation

### ISSUE THREAD

**Issue by dan31** [Starcounter/starcounter.io#52]
@alemoi's work on SQL query isolation and querying from administrator.

**Comment by warpech** [comment]
And the mandatory blog post, which I heard is already waiting for publishing :)

**Comment by alemoi** [comment]
Here is a private draft blog post that i just added: http://starcounter.io/nightly-changes/list-breaking-changes-starting-build-2-0-3500-3/

Not sure if you can see it though, maybe only Administrator and me.

**Comment by miyconst** [comment]
:+1:

**Comment by warpech** [comment]
Great! I can see it when I'm logged in.

Could you edit it to say what was removed? I mean there is information that new flags were added, but not that `PolyjuiceFlag` was removed.

After code changes are published, please also update the Guide. So far I have found these occurences of `PolyjuiceNamespace` in the website:

- http://starcounter.io/tutorials/invoicedemo-part-3/3-5-add-launchpad-icon/
- http://starcounter.io/tutorials/invoicedemo-part-3/3-4-add-launcher-menu-item/

**Comment by alemoi** [comment]
Good point! I added removed flags! And will update tutorials, once pushed.

**Comment by alemoi** [comment]
Ok, since I pushed everything today, the blog post is visible now and here is the docs about SQL isolation that I wrote: http://starcounter.io/guides/sql/sql-isolation/

**Comment by warpech** [comment]
@alemoi the content on the page http://starcounter.io/guides/sql/sql-isolation/ is relevant to Starcounter 2.1+, right? If so, then I will update the page to mention that
