### ISSUE TITLE
Add anchors to the H tags

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter.io#59]
Some of our *how to/guide/wiki* pages are very long, and it would be good to be able to point to a certain section of a page, not just link entire page.

**Comment by warpech** [comment]
Added using [Anchor.js](http://bryanbraun.github.io/anchorjs/#examples)

See http://starcounter.io/guides/tools/administrator/ for example

**Comment by miyconst** [comment]
It adds heading anchors after page loaded, that is why links like this: http://starcounter.io/guides/tools/administrator/#network does not automatically point to the needed section.

**Comment by warpech** [comment]
For me it worked for some reason. 

But now I added an explicit scrolling to the page. 

```js
$(window).load(function(){
  if(location.hash && jQuery(window).scrollTop() == 0) {
	var $one_page_link = jQuery( '<a href="' + location.hash + '">BLE</a>');
	jQuery('body').append( $one_page_link );
    var evt = document.createEvent("MouseEvents");
    evt.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
    $one_page_link[0].dispatchEvent(evt); 
    $one_page_link.remove();    
  }
});
```

Can you try again?

Still I think JS is the best option, because there is no nice WP plugin for that.

**Comment by miyconst** [comment]
Did you clean the cache? It does not work for me, and there is an exception on console: `Uncaught TypeError: $ is not a function`.

**Comment by warpech** [comment]
Oops... Thanks for noticing. Please try again

**Comment by miyconst** [comment]
Now it works.
