### ISSUE TITLE
Document HandlerOptions

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#66]
Document `HandlerOptions` flags like `SkipHandlersPolicy`

**Comment by alemoi** [comment]
Assigned myself!

**Comment by alemoi** [comment]
Documentation added: http://starcounter.io/guides/network/handling-responses/#notable-handler-options

**Comment by warpech** [comment]
Thanks! But why is it on [Creating HTTP responses](http://starcounter.io/guides/network/handling-responses/#notable-handler-options) page, not on [Handling HTTP requests](http://starcounter.io/guides/network/handling-requests/)?

Also: it is never how to provide `HandlerOptions` (as the last parameter to Handle.GET, Handle.POST, etc).

**Comment by alemoi** [comment]
Yeah, will move it. Had same question for myself :) And will write about passing as parameters to Handle and Self.

**Comment by alemoi** [comment]
Moved and extended with example: http://starcounter.io/guides/network/handling-requests/

**Comment by warpech** [comment]
Thanks! I have 2 more notes:

1. Can you remove the words "As you know" from the beginning of the paragraph. This is the only place where `HandlerOptions`, so the reader doesn't have any prior knowledge about it.
2. It says that `HandlerOptions` can be used when calling handlers (using `Self.` interface) but there is no explanation nor example of such use.

**Comment by alemoi** [comment]
Totally legitimate comment! :) Will fix both!

**Comment by alemoi** [comment]
Should be fixed now. Also created a new page for describing database configuration options: http://starcounter.io/guides/database/database-configuration/

**Comment by warpech** [comment]
Thanks! I moved http://starcounter.io/guides/database/database-configuration/ at the end of the Database category, because it is only targeted at advanced users.
