### ISSUE TITLE
Migrate staradmin page

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#74]
From here: https://github.com/Starcounter/Starcounter/wiki/staradmin

Include information from here: https://github.com/Starcounter/Starcounter/issues/2942#issuecomment-149321111

**Comment by warpech** [comment]
Page migrated. I added description of commands: console, delete, help, kill, reload, unload based on the output of `staradmin help <command>`

@per-samuelsson, could please review and add the information log levels that you described here:  https://github.com/Starcounter/Starcounter/issues/2942#issuecomment-149321111. I couldn't find any info about this.

Some commands explained in `staradmin help <command>` do not work. I created issues for them: https://github.com/Starcounter/Starcounter/issues/2973, https://github.com/Starcounter/Starcounter/issues/2974

**Comment by per-samuelsson** [comment]
> Page migrated.

Awesome.

> Some commands explained in staradmin help <command> do not work. I created issues for them:

Yeah, a few have been prepared for, but not implemented. Sorry.

> @per-samuelsson, could please review and add the information log levels that you described here: Starcounter/Starcounter#2942 (comment). I couldn't find any info about this.

There was some in a referenced page about the server log if I remember correctly. I think I wrote some details there. But sure, I can review it and see if I can add anything.

**Comment by per-samuelsson** [comment]
> There was some in a referenced page about the server log if I remember correctly.

https://github.com/Starcounter/Starcounter/wiki/Error-log#using-command-line-tools

**Comment by warpech** [comment]
Thanks! I will move that one as well. 

On a side note, which shorthand for `--database` do you recommend: `--d` or `-d`? Both are used in wiki and both work, but we should use only one to be consistent.

**Comment by per-samuelsson** [comment]
> On a side note, which shorthand for `--database` do you recommend: `--d` or `-d`? Both are used in wiki and both work, but we should use only one to be consistent.

Hmm. What about if we stick to recommended practice of our upcoming `DNX` stack, and the tooling there? Simply b/c its the one I know. They might have a different standard on other stacks/platform.

In `dnx` tooling, they use double hyphens for long versions, single for short.

```C#
star --database=foo app.cs
star -d=foo app.cs
``´

Lets adapt that too. That's OK w/ u @warpech?

**Comment by warpech** [comment]
Perfect! That's common on UNIX, too. I'll adjust the docs

**Comment by per-samuelsson** [comment]
> I'll adjust the docs :+1:

**Comment by warpech** [comment]
> I'll adjust the docs

Done! Now `-d` is used everywhere except http://starcounter.io/guides/tools/staradmin/#basic-usage

**Comment by per-samuelsson** [comment]
> Done! Now -d is used everywhere except http://starcounter.io/guides/tools/staradmin/#basic-usage

Super! I'll review the page as I promised, either this weekend, or sometime next week.
