### ISSUE TITLE
"Register" button does not redirect in Firefox

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#76]
<img width="1552" alt="screenshot 2015-10-30 18 33 24" src="https://cloud.githubusercontent.com/assets/566463/10853123/c8164fdc-7f34-11e5-83cd-78f0d58592e3.png">

Clicking the "Register" button in Firefox creates the user, but does not redirect to logged in page.

Clicking "Sign in" works as expected.

**Comment by miyconst** [comment]
The issue once again was with IE & FF not executing scripts from imported templates. Fixed now. Will deploy tomorrow with the newest version of Starcounter.
