### ISSUE TITLE
Explain importing Web Components

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#8]
As @miyconst wrote in issue https://github.com/Polyjuice/Launcher/issues/87:

> To avoid this issue all of the bower components should be installed to /sys/ directory, not /bower_components/.

This should be turned into a starcounter.io article about working with Web Components

**Comment by miyconst** [comment]
Here is the first version: http://starcounter.io/guides/apps/working-with-webcomponents/

**Comment by warpech** [comment]
Nice, thanks! Some issues:

1. use the correct W3C letter casing in page title and content: "Web Components", "HTML Imports"
2. the Next/Prev buttons lead to wrong pages. This can be fixed by changing "Order" in WordPress page admin.

**Comment by miyconst** [comment]
Done.

**Comment by warpech** [comment]
Looks good!
