### ISSUE TITLE
Adjust the design of the App Hub

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#80]
The gray bars in the App Hub should take the whole width of the screen and use the same styles as the grey bars on the home page.

Compare home page:

![screenshot 2015-11-03 17 42 49](https://cloud.githubusercontent.com/assets/566463/10938419/613c35c8-82fa-11e5-8475-d2131f3af922.png)

With the App Hub:

![screenshot 2015-11-03 17 42 34](https://cloud.githubusercontent.com/assets/566463/10938425/6a4e44ee-82fa-11e5-97b1-21bd94328f2b.png)

![screenshot 2015-11-03 17 42 42](https://cloud.githubusercontent.com/assets/566463/10938427/6fac2384-82fa-11e5-8bc7-6603781003aa.png)

**Comment by miyconst** [comment]
Done.
