### ISSUE TITLE
I can sign up to get news without email address

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter.io#83]
The sign up to get news form passes through without email:

![image](https://cloud.githubusercontent.com/assets/6435556/11036147/018de8b4-86f7-11e5-8157-00058bf6d71f.png)

![image](https://cloud.githubusercontent.com/assets/6435556/11036152/081c8b22-86f7-11e5-91ca-0f5324b34008.png)

**Comment by miyconst** [comment]
This was also reported by TargetEveryOne guys.

Should really be fixed.

cc @warpech

**Comment by warpech** [comment]
@sabrinareflex can we add some validation to the form?

**Comment by sabrinareflex** [comment]
The .io form used to be required so I don’t know why it changed but it’s now fixed!

**Comment by warpech** [comment]
Works good now, thanks!
