### ISSUE TITLE
Description of sample tutorial is difficult to understand

### ISSUE THREAD

**Issue by k-rus** [Starcounter/starcounter.io#87]
(I don't know if it is appropriate place for my report)

[The tutorials web page](http://starcounter.io/tutorials/) has following description:

>Sample app: Part 1 – build a Invoice Demo SPA displaying show a single invoice with rows, computed totals and buttons: Add Row, Save and Cancel

It is really hard to understand. Especially, the combination `displaying show`.

**Comment by warpech** [comment]
> (I don't know if it is appropriate place for my report)

This is the most appropriate place!

> It is really hard to understand. Especially, the combination displaying show.

Thanks! I Rewrote the descriptions. Does it look better now?

**Comment by k-rus** [comment]
It is better now, but it should be improved to align with other tutorial description. What's about:
>Part1 - build an Invoice Demo SPA with a single invoice, calculated properties and Add Row, Save and Cancel buttons

I removed colons, since two levels of colons is not good and to align with Part 2 description.

**Comment by k-rus** [comment]
Sorry that I haven't updated the text directly, since I don't remember how to do it and how to find instructions.

**Comment by warpech** [comment]
> Part1 - build an Invoice Demo SPA with a single invoice, calculated properties and Add Row, Save and Cancel buttons

I agree, thanks! I have applied the proposed change.

WordPress instructions are here: https://github.com/Starcounter/CompanyTrack/issues/110#issuecomment-151748540

Your access credentials can be obtained by clicking on "Lost password" here: http://starcounter.io/wp-admin/ (username the same as on GitHub).
