### ISSUE TITLE
Page authors on the web site are not content authors

### ISSUE THREAD

**Issue by k-rus** [Starcounter/starcounter.io#89]
Each page on starcounter.io has public information about the author. However, as I can see there are many cases when the authors are not actual authors of the page content. It would be nice to fix either by hiding authoring clause from public or fixing actual content author. The second option requires manual fix and difficult to maintain.

**Comment by warpech** [comment]
The purpose is to give credit and motivation to the original author of the blog posts. I will try to do my best to fix this, cause I still have links to the original page authors of the wiki pages. It is not very hard to maintain, just hard to apply for migrated pages.

**Comment by warpech** [comment]
I did it the changes based at the original page author or prevalent author, if there was a person who rewrote most of the page. 

Of course it still could be improved, for example some pages have multiple authors and all should be listed.

The reason why this information is displayed is to give credit and motivation to page authors. Of course, this is the team's decision to keep it or not, but I will give it another try.
