### ISSUE TITLE
Remove or update Guide disclaimer

### ISSUE THREAD

**Issue by k-rus** [Starcounter/starcounter.io#90]
[The guide web page](http://starcounter.io/guides/) contains the following disclaimer:

>The Guides section is under construction. Check out our WIKI ON GITHUB for more content.

I am not sure if it is still valid. The most of the content is already moved into starcounter.io and, furthermore, the github wiki contains mainly stubs. I suggest to remove the disclaimer, since finding useful information on github wiki is really difficult now due to the empty stubs.

**Comment by warpech** [comment]
Good point! I will do it

**Comment by warpech** [comment]
Fixed on the page http://starcounter.io/guides/
