### ISSUE TITLE
Explain how the wwwroot directory is discovered

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#94]
On the page http://starcounter.io/guides/network/static-file-server/

**Comment by per-samuelsson** [comment]
This one's done right @warpech?

**Comment by warpech** [comment]
Looking very good, thanks! 

For people who read fast, could this initial paragraph:

> When your application start, Starcounter support exposing static resources by convention.

Be changed to say what is the convention? Below follows an example but it is not clear that the convention is to call the folder **wwwroot** (maybe the convention is that it just needs to be the last folder in directory?).

> will add wwwroot as a resource directory explicitly.

Did you mean implicitly?
