### ISSUE TITLE
Using Http and Node

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#98]
[Creating HTTP responses](http://starcounter.io/guides/network/handling-responses/) contains a phrase:

> Please refer to Using Http and Node article for more information.

@alemoi, do you know what article is meant here?

**Comment by warpech** [comment]
This page, I guess? http://starcounter.io/guides/network/external-http-calls-and-node-usage/

**Comment by warpech** [comment]
After reading - yeah, that must be the article. Sorry for bothering :)

**Comment by alemoi** [comment]
Thanks for fixing :)
